### ISSUE TITLE
Working with the basename parameter

### ISSUE THREAD

**Issue by Mauladen** [artalar/react-router-typed-object#5]
I don't really understand what I might be doing wrong or this library is not suitable for my case

At the moment, I'm setting `basename: '/app'` according to the type that `createRouter` returns to me

But at the time of use, typing `ROUTER` obliges me to write like this `ROUTER['/app/...']`, which in my case leads to the fact that I get a transition to `/app/app/.....`

Here is an example of usage:
`<Link to={ROUTER['/app/...'].path()}>`

**Comment by artalar** [comment]
Fixed in `1.0.2`

**Comment by Mauladen** [comment]
@artalar thanks for the quick fix
